version: '3.8'

services:
  spark-master:
    image: spark-base:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"  # Spark Master Port
      - "8080:8080"  # Spark Master Web UI
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - ./spark-config:/opt/spark/conf

  spark-worker-1:
    image: spark-base:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./spark-config:/opt/spark/conf

  spark-worker-2:
    image: spark-base:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./spark-config:/opt/spark/conf

  spark-worker-3:
    image: spark-base:latest
    container_name: spark-worker-3
    hostname: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./spark-config:/opt/spark/conf

  spark-worker-4:
    image: spark-base:latest
    container_name: spark-worker-4
    hostname: spark-worker-4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./spark-config:/opt/spark/conf

networks:
  default:
    driver: bridge