version: "3.8"
services:
  db:
    image: postgres
    container_name: custom_pgdb_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev-password
    volumes:
      - ./pg_local_storage:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: custom_pgadmin_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev-user@dummy.com
      PGADMIN_DEFAULT_PASSWORD: dev-password
    volumes:
      - ./pgadmin_local_storage:/var/lib/pgadmin
